.PHONY: 3.8-slim-buster-rmq 3.8-slim-buster 3.9-slim-buster-rmq 3.9-slim-buster


3.8-slim-buster-rmq:
	docker build -t dcr.teletraan.io/public/python:3.8-slim-buster-rmq ./3.8-slim-buster-rmq
	docker push dcr.teletraan.io/public/python:3.8-slim-buster-rmq
	
3.8-slim-buster:
	docker build -t dcr.teletraan.io/public/python:3.8-slim-buster ./3.8-slim-buster
	docker push dcr.teletraan.io/public/python:3.8-slim-buster

3.9-slim-buster-rmq:
	docker build -t dcr.teletraan.io/public/python:3.9-slim-buster-rmq ./3.9-slim-buster-rmq
	docker push dcr.teletraan.io/public/python:3.9-slim-buster-rmq
	
3.9-slim-buster:
	docker build -t dcr.teletraan.io/public/python:3.9-slim-buster ./3.9-slim-buster
	docker push dcr.teletraan.io/public/python:3.9-slim-buster
